#!/usr/bin/env python3

class Node:
   
   def __init__(self, data):
      self.data = data
      self.next = None

class Linkedlist:
    
     def __init__(self):
         self.head = head
         self.size = 0
     
     def insert(self, value):
        new_node = Node(value)
        if self.head is None:
              head = new_node
        curr = head
        while curr:
          curr = curr.next
        curr.next = new_node
        
     def traverse(self):
          curr = head
          nodes = []
          while curr:
               nodes.append(curr.data)
               curr = curr.next
          return "->".join(nodes) if nodes else return "no node in linkedin list"

LL = Linkedlist()
ll.insert(1)
ll.insert(2)
ll.insert(5)
print(ll.traverse())

    
              
       
